apiVersion: v1
kind: Pod
metadata:
  name: my-sa-pod
spec:
    serviceAccountName: my-sa
    containers:
    - name: busybox
      image: radial/busyboxplus:curl
      command: ['sh', '-c', 'while true; do curl -s --header "Authorization: Bearer $(cat /var/run/secretes/kubernetes.io/serviceaccount/token)" --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt https://kubernetes.api/v1/namespaces/defualt/pods; sleep 5; done']