apiVersion: v1
kind: Pod
metadata:
  name: resource-request-limit-quota-pod
  namespace: resources-pod
spec:
  contianers:
  - name: busybox
    image: busybox:stable
    command: ['sh', '-c', 'while true; do echo Running....; sleep 5; done']
    resources:
      rquests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: apple
  namespace: dev
spec:
  contianers:
  - name: nginx
    image: nginx:stable
    command: ['sh', '-c', 'while true; do echo Running....; sleep 5; done']
    resources:
      rquests:
        memory: "256Mi"
        cpu: "250m"
