apiVersion: v1
kind: Pod
metadata:
  name: readiness-liveness-probe
spec:
  containers:
  - name: readiness-liveness
    image: busybox:stable
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 5
    command: ['sh', '-c', 'while true; sleep 10; done']
