apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe
spec:
  containers:
  - name: liveness-probe
  image: busybox:stable
  command: ['sh', '-c', 'while true; sleep 10; done']
  livenessProbe:
    exec:
      command: ['echo', 'healthcheck']
    initialDelaySeconds: 5
    periodSeconds: 5