apiVersion: v1
kind: Pod
metadata:
  name: broken-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.20.q
    livenessProbe:
      httpGet:
        path: /
        port: 81
      initialDelaySeconds: 5
      periodSeconds: 5
#        failureThreshold: 1
#        successThreshold: 1
#        timeoutSeconds: 1