apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  sensitive.data: c2VjcmV0LWRhdGE=
  password.txt: cGFzc3dvcmQ=

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-code
  namespace: secure
type: Opaque
data:
  code: dHJ1c3RubzEK