apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: busybox:stable
      command: ['sh', '-c', 'echo SENSITIVE_STUFF; cat config/password.txt']
      env:
      - name: SENSITIVE_STUFF
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: sensitive.data
      volumeMounts:
      - name: secret-config
        mountPath: /etc/secret-volume
        readOnly: true
volumes:
  - name: secret-config
    secret:
      secretName: my-secret
      items:
      - key: password.txt
        path: password.txt
