apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-green-test
      color: green
  template:
    metadata:
      labels:
        app: blue-green-test
        color: green
    spec:
      containers:
      - name: blue-green-test
        image: mudasarhashmi/ckad-nginx:blue
        ports:
        - containerPort: 80